name = "GraphPlot"
uuid = "a2cc645c-3eea-5389-862e-a155d0052231"
authors = ["JuliaGraphs"]
version = "0.4.1"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArnoldiMethod = "0.0.4"
ColorTypes = "0.9"
Colors = "0.11"
Compose = "0.7, 0.8"
LightGraphs = "1.1"
VisualRegressionTests = ">= 0.2"
julia = "1"

[extras]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["Test", "Cairo", "ImageMagick", "VisualRegressionTests"]
